global:
  storageClass: "standard"

controller:
  replicaCount: 1

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  heapOpts: "-Xms256m -Xmx512m"

  persistence:
    enabled: true
    size: 1Gi

  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 60

  listeners:
    client:
      name: PLAINTEXT
      containerPort: 9094
      protocol: PLAINTEXT

  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIPs:
      - 127.0.0.1 # 또는 kind 클러스터가 바인딩된 Docker 호스트 IP
      autoDiscovery:
        enabled: false
    external:
      advertisedListeners:
      - PLAINTEXT://localhost:9094

  configurationOverrides:
    "listeners": PLAINTEXT://:9094
    "advertised.listeners": PLAINTEXT://localhost:9094
    "listener.security.protocol.map": PLAINTEXT:PLAINTEXT

broker:
  replicaCount: 0

metrics:
  kafka:
    enabled: false
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false
