global:
  storageClass: "standard"

controller:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  heapOpts: "-Xms256m -Xmx512m"
  persistence:
    enabled: true
    size: 1Gi

  # Probe 설정 조정
  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 60  # 10분 동안 시도

broker:
  replicaCount: 0 # broker-only 노드는 불필요

listeners:
  client:
    name: PLAINTEXT
    containerPort: 9092
    protocol: PLAINTEXT

externalAccess:
  enabled: true
  controller:
    service:
      type: LoadBalancer
      loadBalancerIPs:
      - 172.19.255.201 # MetalLB에서 설정한 IP 범위 내에서 1개 사용
      annotations:
        metallb.universe.tf/address-pool: first-pool

metrics:
  kafka:
    enabled: false
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false
