apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filedepot-pvc
  namespace: filedepot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
