replicaCount: 1

image:
  repository: host.docker.internal:5001/filedepot
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000
  annotations:
    metallb.universe.tf/address-pool: first-pool
  loadBalancerIP: 172.19.255.202

kafka:
  bootstrapServers: kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
  topic: filedepot-topic

resourcenv:
  - name: ENVIRONMENT
    value: "dev"
  - name: PROJECT_NAME
    value: "filedepot"
  - name: DATABASE_URL
    value: "sqlite:///./test.db"
  - name: FIRST_SUPERUSER
    value: "admin@example.com"
  - name: FIRST_SUPERUSER_PASSWORD
    value: "admin123"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 12
