apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filedepot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ch0992/opensearch_proxy.git
    targetRevision: HEAD
    path: Infra/argocd/filedepot/helm
    helm:
      valueFiles:
      - values.yaml
      - values-custom.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: filedepot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
