---
clusterName: "opensearch-cluster"
nodeGroup: "master"

# Docker Desktop 환경에 맞게 single-node로 설정
singleNode: true

# OpenSearch roles
roles:
  - master
  - ingest
  - data
  - remote_cluster_client

replicas: 1
majorVersion: ""

# Resource 설정 최적화
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Java heap 설정 최적화
opensearchJavaOpts: "-Xmx512M -Xms512M"

# Security 설정
securityConfig:
  enabled: false
  actionGroupsSecret:
    name: ""
  configSecret:
    name: ""
  internalUsersSecret:
    name: ""
  rolesSecret:
    name: ""
  rolesMappingSecret:
    name: ""
  tenantsSecret:
    name: ""

# Anti-affinity 설정
antiAffinity: "soft"

# Storage 설정
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: "1Gi"
  storageClass: "hostpath"

# Service 설정
service:
  type: ClusterIP
  port: 9200
  transportPort: 9300
  nodePort: ""
  loadBalancerIP: ""
  annotations: {}

# Monitoring 설정
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: ""
    interval: "10s"
    scrapeTimeout: "10s"
    scheme: http

# Ingress 설정
ingress:
  enabled: false

# Pod Security Context
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

# Sysctl 설정 (Docker Desktop에서는 비활성화)
sysctl:
  enabled: false

# 초기화 설정
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    discovery.type: single-node
    network.host: 0.0.0.0
    bootstrap.memory_lock: false
    
    # Security plugin 비활성화
    plugins.security.disabled: true

# Readiness probe 설정
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Liveness probe 설정
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
