# Docker Desktop 환경에 최적화된 OpenSearch 설정
clusterName: "opensearch-cluster"
nodeGroup: "master"

# Single-node 설정
singleNode: true

# Resource 설정
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Java heap 설정
opensearchJavaOpts: "-Xmx512M -Xms512M"

# Storage 설정
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: "1Gi"
  storageClass: "hostpath"

# Security 설정
securityConfig:
  enabled: false
  actionGroupsSecret:
    name: ""
  configSecret:
    name: ""
  internalUsersSecret:
    name: ""
  rolesSecret:
    name: ""
  rolesMappingSecret:
    name: ""
  tenantsSecret:
    name: ""

# Service 설정
service:
  type: ClusterIP

# Monitoring 설정
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "10s"
    scrapeTimeout: "10s"

# 초기화 설정
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    discovery.type: single-node
    network.host: 0.0.0.0
    bootstrap.memory_lock: false
    plugins.security.disabled: true
