apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafka.brokerConnect }}
            - name: JVM_OPTS
              value: {{ .Values.jvm.opts }}
            {{- if .Values.kafka.properties }}
            - name: KAFKA_PROPERTIES
              value: {{ .Values.kafka.properties }}
            {{- end }}
            {{- if .Values.kafka.truststore }}
            - name: KAFKA_TRUSTSTORE
              value: {{ .Values.kafka.truststore }}
            {{- end }}
            {{- if .Values.kafka.keystore }}
            - name: KAFKA_KEYSTORE
              value: {{ .Values.kafka.keystore }}
            {{- end }}
            {{- if .Values.kafka.propertiesFile }}
            - name: KAFKA_PROPERTIES_FILE
              value: {{ .Values.kafka.propertiesFile }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
