apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ch0992/opensearch_proxy.git
    targetRevision: HEAD
    path: Infra/argocd/kafdrop/helm
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
