kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: filedepot
nodes:
- role: control-plane
  extraPortMappings:
  # MinIO - 콘솔 및 S3 API
  - containerPort: 9000
    hostPort: 9000
    protocol: TCP
  # OpenSearch - REST API
  - containerPort: 9200
    hostPort: 9200
    protocol: TCP
  # Kafdrop - Kafka UI
  - containerPort: 9100
    hostPort: 9100
    protocol: TCP
  # FileDepot - FastAPI 기반 서비스
  - containerPort: 8000
    hostPort: 8000
    protocol: TCP
  # Kafka Broker - 외부 접속용 PLAINTEXT 포트
  - containerPort: 9094
    hostPort: 9094
    protocol: TCP
  # Argo CD - Insecure UI 포트
  - containerPort: 8070
    hostPort: 8070
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://localhost:5001"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5001"]
    endpoint = ["http://host.docker.internal:5001"]
