kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: desktop
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000  # OpenSearch HTTP
    hostPort: 30000
  - containerPort: 30001  # OpenSearch Transport
    hostPort: 30001
  - containerPort: 30002  # Kafka
    hostPort: 30002
  - containerPort: 30003  # Kafka Manager
    hostPort: 30003
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
- role: worker

